name: Generate and Deploy Doxygen Documentation

on:
  push:
    branches:
      - main  # Adjust if you are using a different branch

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Doxygen
      run: sudo apt-get install -y doxygen

    - name: Generate Doxygen docs
      run: doxygen portfolio/doxygen/Doxyfile

    - name: Deploy docs to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: portfolio/doxygen/documentation
