name: Generate Doxygen Documentation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Doxygen
      run: sudo apt-get install doxygen

    - name: Create documentation directory
      run: mkdir -p documentation

    - name: Run Doxygen
      run: doxygen portfolio/doxygen/Doxyfile
