name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout code

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If you have dependencies, you should install them here
        # For example:
        # pip install -r portfolio/github-actions/requirements.txt

    - name: Run tests
      run: |
        python portfolio/github-actions/test_script.py
